# -*- coding: utf-8 -*-
"""yolov5_collisionDetect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12RuzU6ezB-9Hc7GcHyxqUvnjAEnvJtjo
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -r requirements.txt

from google.colab import drive
drive.mount('/content/gdrive')
!ln -s /content/gdrive/My\ Drive/ /mydrive
!ls /mydrive

!unzip /content/data.zip -d /content/yolov5/data

!python3 /content/yolov5/train.py --img 640 --batch 16 --epochs 50 --data /content/yolov5/data/dataset.yaml --weights yolov5s.pt

!python3 /content/yolov5/detect.py --img 640 --conf 0.25 --source /content/yolov5/collision_video.mp4 --weights /content/yolov5/runs/train/exp/weights/best.pt

